# Generated by Django 5.0.4 on 2024-04-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("processing", "Обработка"),
                            ("in_transit", "В пути"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=255,
                    ),
                ),
                ("expected_delivery_date", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(max_length=255)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.purchase",
                    ),
                ),
            ],
        ),
    ]
